name: Publish package to NPM

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checkout to target branch
      - uses: actions/checkout@v2
        with:
          # Pull submodules
          submodules: 'recursive'

      # Setup node environment
      - uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org/

      # Prepare, build and publish project
      - name: Install dependencies
        run: yarn

      - name: Build output files
        run: yarn build

      - name: Publish the package with a NEXT tag
        run: yarn publish --access=public --tag=next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
